### ISSUE TITLE
Where does the data come from?

### ISSUE THREAD

**Issue by manulitopetito** [jalapic/engsoccerdata#10]
Hi!

Where does the data for the shot positions come from? Is it a reliable source that can be cited in a publication? Thanks!

**Comment by jalapic** [comment]
It comes from multiple sources (see ReadMe).  Several of these sources actually have copied errors from other sources, therefore I had to do many manual checks and cross-references to ensure all data are correct.

**Comment by janeshdev** [comment]
How often do you update these data sources ?

**Comment by jalapic** [comment]
The data get updated at the beginning of the year (Jan1) and on July 1 when all competitions have ended.  I may write some additional code to get data in real-time but have not yet. If anyone wants to contribute that -  I'm open to it.
