### ISSUE TITLE
Add Major League Soccer (MLS) data to engsoccerdata

### ISSUE THREAD

**Issue by aqsmith08** [jalapic/engsoccerdata#22]
Consider using [openfootball/major-league-soccer](https://github.com/openfootball/major-league-soccer) or another open source option.

**Comment by jalapic** [comment]
Yes, I will add.  Can get data into a results df format.  These data are mainly ok, but there are errors: e.g. for 2014 season:

 `Sat Oct/11 23:30 Real Salt Lake           20- San Jose Earthquakes`

so would like to double-verify with another source. - probably easiest to do by making league tables after got the data into correct format.

**Comment by jalapic** [comment]
Also, they store data in annoyingly inconsistent formats - e.g. different subheadings and 2015 is a completely different format !   - I guess this is why having an R package with everything in tidy format is useful.

**Comment by aqsmith08** [comment]
Yes, exactly right! For what it's worth, I created a script that returns all the "right" columns for the 2016 season based on the `txt` [file](https://github.com/openfootball/major-league-soccer/blob/master/2016/mls.txt) that's there. Having said that, the script doesn't handle the inconsistent format (yet) because previous season data is all different. An example is the 2014 `txt` [file](https://github.com/openfootball/major-league-soccer/blob/master/2014/mls.txt). 

I'm not sure if I will have time to tackle this week so happy to share what I've started. I also didn't know if we could source the data somewhere else where it's in a better format (so I didn't want to invest too heavily). Just let me know.

**Comment by jalapic** [comment]
No problem - I'll have the data 2005-2016 put into the package `/data` and `/raw-data` folders in tidy format in an hour or so.  I've worked out the errors.    I believe I had some pre-2005 MLS data stored somewhere - but I'll focus on this first before going looking for that.

**Comment by aqsmith08** [comment]
Love it. Thanks for your work here!

**Comment by jalapic** [comment]
All MLS gamee from 2005-2016 are now added in the dataframe `mls`. Teamnames have been regularized and added to `teamnames`. Also added to `mls` is conference affiliation of each team.  Both regular season and playoff games included.   If anybody wants to help with pre2005 data - please do !
