### ISSUE TITLE
Add Conference (5th tier England) data

### ISSUE THREAD

**Issue by jalapic** [jalapic/engsoccerdata#34]
5th tier has been a national league since 1979/80 season - add data.

Note: check `maketable_eng` function for different tie-breaking and points procedures up to 1981/82 season.

**Comment by jalapic** [comment]
Have added data from 1999/2000 - 2016/17.  Can get results from prior to this (league came into existence in 1974/75) but cannot find a source that also has dates of matches.  Will add when can find it - and also change table function then.

**Comment by jalapic** [comment]
@RobWHickman did this - needs updating but exists.

**Comment by RobWHickman** [comment]
I think the data is really interesting at this level but I would strongly caution about updating it- at this level so many teams change their names, or have ambiguous names, you really want to set aside a weekend just to update data

**Comment by jalapic** [comment]
![image](https://user-images.githubusercontent.com/7896861/97120961-14f93700-16e9-11eb-98b8-954d47881380.png)

**Comment by jalapic** [comment]
because I'm a York City fan - I have motivation to try and get the data all the way down to the 6th tier.......  or further should we get relegated even more in the future.
