### ISSUE TITLE
Add South Africa League and other competitions

### ISSUE THREAD

**Issue by sibusiso16** [jalapic/engsoccerdata#42]
Hi James. I trust you are well. I would like to help and add the South Africa league to your package. I would like to know what’s the process of doing this.

**Comment by jalapic** [comment]
Hey thanks.  The best way to help would be to provide  a csv or excel file  with all the results.   That can  be uploaded here.  If you have deeper knowledge of R, you can add  directly to the package via a pull request.  If not, then a csv or excel file is fine and I can add to the package.

**Comment by sibusiso16** [comment]
Hi James. Thanks a lot. Currently I have 2017 results. Can I send you this while I work on the previous seasons or should I send you all the seasons at one go?

**Comment by jalapic** [comment]
yes, please send that - e.g. upload to a gist would be fine.  Then I can see what format it  is in and make suggestions.  To put into the package though, we'll do all at once.

**Comment by sibusiso16** [comment]
Hi James. Here is a gist link to the 2017 South Africa PSL. https://gist.github.com/sibusiso16/99b54fd727c697b62a0f491ee886395c. I tried to follow the format with variable names.

**Comment by jalapic** [comment]
looks great  - thanks.  Yes, that will work well.   One thing to be careful of when collecting multiple seasons is to make sure that the teamnames are consistent across seasons.  e.g. if the name has "FC" in it in 2017, make sure it's the same for all seasons - this helps users when doing searches across years.

thanks

**Comment by sibusiso16** [comment]
Thanks a lot. I will work on all the seasons and keep the names the same. :-) Thanks again

**Comment by sibusiso16** [comment]
Hi James. I trust you are well. Here is the link to the data for South African's PSL results since 2008, https://gist.github.com/sibusiso16/8346326c482bb38c50559faebb5110a6. I did make the mistake of adding "FC" to one team and i didn't include it in other seasons. But i did fix it. Thanks...

**Comment by sibusiso16** [comment]
Hi James. I have updated the South Africa's PSL results. Now it's from 2002. 2002 is the year in which the league was reduce to 16 teams from 18 teams. 

here is the link with the updated results...
https://gist.github.com/sibusiso16/64f1666ce90f24b436c4162d5ef0debf

**Comment by sibusiso16** [comment]
Hi James. I trust you are well. I just wanted to know how do you update your data on your package?

**Comment by jalapic** [comment]
sorry - got busy, but will do this tonight !

**Comment by sibusiso16** [comment]
Hi James. Thanks. Can I provided you with the updated csv that will include this weekend’s games? Going forward how will I provide you with scores? Do I need to regenerate the csv with the full history?

**Comment by pssguy** [comment]
@jalapic any ETA for this?

**Comment by jalapic** [comment]
@sibusiso16 @pssguy OK !  Sorry for the delay - it should work now and be on the most up to date GitHub version.  Thank you for your help and contribution!

**Comment by sibusiso16** [comment]
Thanks a lot James. 

Here is the link to the updated data (up-to 26-11-2017) https://gist.github.com/sibusiso16/c86d9aef97cbf804b0a66b7e57fc6900 

How do I provide you with the updates going forward?

**Comment by jalapic** [comment]
The best way is to make a function that will directly scrape just this seasons (or the current season) data.  That way, the older season data never changes but it's easy for users to get the current data without having to update the package after every result.
