### ISSUE TITLE
England_current() returns same column names but different column types

### ISSUE THREAD

**Issue by padpadpadpad** [jalapic/engsoccerdata#48]
1. Fantastic package!
2. england_current() returns the same column names as in data(england), but the column types are different. For example, division is numeric whereas it is a character in data(england). 

This causes an error when trying to bind these rows with dplyr::bind_rows().

Would work much better if these were all the same. Either all characters or numeric.

**Comment by jalapic** [comment]
thanks - that's a bug. Previously they were all the same. I will fix as soon as I get a chance.

**Comment by jalapic** [comment]
I fixed this a while ago - just closing this now.  Should work for all European leagues.
