### ISSUE TITLE
League position

### ISSUE THREAD

**Issue by Garryf** [jalapic/engsoccerdata#53]
Hi, I would be interesting in adding league positions and team form into an analysis.  It would be useful if I could get info on each time , with regards to position in league. shots/shots on target ect. for each of the teams in a specific match. It probably already been done, but I want to weight a match prediction based on the recent league position and how the team has performed against other teams close or further away from them in the league. Getting the league table data and all other stats for a team with a time stamp or period would be useful. is there anyway I can get week by week league table data? 

thanks

Garry

**Comment by Habet** [comment]
If you use R, i have a function developed for it here - https://github.com/Habet/CSE270

**Comment by jalapic** [comment]
The three `maketable()` functions in the package is able to do this-   dataframes just need to be filtered by date.  Points deductions are their own issue, but there is some effort to keep tabs of deductions for some leagues - see `maketable_eng()`
