### ISSUE TITLE
Game-by-game Shiny App "greyed out"

### ISSUE THREAD

**Issue by aashanand** [jalapic/engsoccerdata#7]
One of the example apps you provided appears to have been terminated (could be because it exceeded its RAM allocation).

https://jalapic.shinyapps.io/gamebygame/

**Comment by jalapic** [comment]
This is actually to do with the source of the data ESPN.co.uk changing the way in which they format their data tables on line.   I don't think it is a quick fix - probably requires me rewriting the code.
