### ISSUE TITLE
R version 3.50 required?

### ISSUE THREAD

**Issue by ChrisHarbron** [jalapic/engsoccerdata#70]
Hi,

I'm getting an error message when I try and install the package : ERROR: this R is version 3.6.2, package 'engsoccerdata' requires R >=  3.50
I assume the requirements should be >=3.5.0

**Comment by Sereton** [comment]
Same error here

**Comment by jalapic** [comment]
Thanks for the heads up.  I'm not sure what would have happened to get this error. But I will look into it.

**Comment by jalapic** [comment]
@Sereton   @ChrisHarbron  I tried updating the .Description and tried an example install.  It seemed to work ok for me.  Could you try again and see if it works?

**Comment by ChrisHarbron** [comment]
Thanks @jalapic , that works for me now too.
