### ISSUE TITLE
england_current() issue

### ISSUE THREAD

**Issue by bassamsdata** [jalapic/engsoccerdata#74]
it shows an issue as the following :( 

`Error:
! Assigned data `as.numeric(hgvg[, 1])` must be compatible with existing data.
✖ Existing data has 559 rows.
✖ Assigned data has 560 rows.
ℹ Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
Warning messages:
1: In matrix(unlist(strsplit(x$FT, "-")), ncol = 2, byrow = T) :
  data length [1119] is not a sub-multiple or multiple of the number of rows [560]
2: In make_data(x2) : NAs introduced by coercion`

I tried with R v4.1 and 4.2 but the same error

**Comment by jalapic** [comment]
sorry about being slow with this package.  I believe that it is fixed and working now.
